swagger: '2.0'
info:
  title: Gcash API
  x-ibm-name: gcash-api
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - invoke:
          version: 2.0.0
          title: invoke
          backend-type: detect
          header-control:
            type: blocklist
            values: []
          parameter-control:
            type: allowlist
            values: []
          timeout: 60
          verb: keep
          chunked-uploads: true
          persistent-connection: true
          target-url: https://gcash-api-2.onrender.com/payments/{id}
          follow-redirects: false
          inject-proxy-headers: true
  properties:
    target-url:
      description: The URL of the target service
      encoded: false
      value: https://gcash-api-2.onrender.com/payments
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
  catalogs:
    Sandbox:
      properties: {}
  application-authentication-source: []
  servers:
    - url: https://api.eu-central-a.apiconnect.ibmappdomain.cloud/api-connect-t7/sandbox/gcash-api
      description: ''
      type:
        - production
        - development
  oauth-servers: []
basePath: /gcash-api
paths:
  /:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  client_secret:
    type: apiKey
    x-key-type: client_secret
    name: X-IBM-Client-Secret
    in: header
security:
  - clientID: []
    client_secret: []
schemes:
  - https
parameters:
  id:
    name: id
    required: true
    in: query
    type: string
